// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __displayControl_client_context_t_h
#define __displayControl_client_context_t_h

#include "displayControl_client_proc.h"

#include "displayControl_types.h"


struct displayControl_client_context_t {

    FBPost_client_proc_t FBPost;
    postLayer_client_proc_t postLayer;
    postAllLayersDone_client_proc_t postAllLayersDone;
    getDisplayWidth_client_proc_t getDisplayWidth;
    getDisplayHeight_client_proc_t getDisplayHeight;
    getDisplayFPS_client_proc_t getDisplayFPS;
    getDisplayXDpi_client_proc_t getDisplayXDpi;
    getDisplayYDpi_client_proc_t getDisplayYDpi;
    postVirtualDisplay_client_proc_t postVirtualDisplay;
    postAllVirtualDisplaysDone_client_proc_t postAllVirtualDisplaysDone;
    postBoForScreenRecord_client_proc_t postBoForScreenRecord;
    postCaptureScreenColorBuffer_client_proc_t postCaptureScreenColorBuffer;
    authenticateMagic_client_proc_t authenticateMagic;
     virtual ~displayControl_client_context_t() {}

    typedef displayControl_client_context_t *CONTEXT_ACCESSOR_TYPE(void);
    static void setContextAccessor(CONTEXT_ACCESSOR_TYPE *f);
    int initDispatchByName( void *(*getProc)(const char *name, void *userData), void *userData);
    virtual void setError(unsigned int  error){ (void)error; };
    virtual unsigned int getError(){ return 0; };
};

#endif
