// Generated Code - DO NOT EDIT !!
// generated by 'emugen'


#include <string.h>
#include "displayControl_client_context.h"


#include <stdio.h>

int displayControl_client_context_t::initDispatchByName(void *(*getProc)(const char *, void *userData), void *userData)
{
    FBPost = (FBPost_client_proc_t) getProc("FBPost", userData);
    postLayer = (postLayer_client_proc_t) getProc("postLayer", userData);
    postAllLayersDone = (postAllLayersDone_client_proc_t) getProc("postAllLayersDone", userData);
    getDisplayWidth = (getDisplayWidth_client_proc_t) getProc("getDisplayWidth", userData);
    getDisplayHeight = (getDisplayHeight_client_proc_t) getProc("getDisplayHeight", userData);
    getDisplayFPS = (getDisplayFPS_client_proc_t) getProc("getDisplayFPS", userData);
    getDisplayXDpi = (getDisplayXDpi_client_proc_t) getProc("getDisplayXDpi", userData);
    getDisplayYDpi = (getDisplayYDpi_client_proc_t) getProc("getDisplayYDpi", userData);
    postVirtualDisplay = (postVirtualDisplay_client_proc_t) getProc("postVirtualDisplay", userData);
    postAllVirtualDisplaysDone = (postAllVirtualDisplaysDone_client_proc_t) getProc("postAllVirtualDisplaysDone", userData);
    postBoForScreenRecord = (postBoForScreenRecord_client_proc_t) getProc("postBoForScreenRecord", userData);
    postCaptureScreenColorBuffer = (postCaptureScreenColorBuffer_client_proc_t) getProc("postCaptureScreenColorBuffer", userData);
    authenticateMagic = (authenticateMagic_client_proc_t) getProc("authenticateMagic", userData);
    return 0;
}

