// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __displayControl_client_ftable_t_h
#define __displayControl_client_ftable_t_h


static const struct _displayControl_funcs_by_name {
    const char *name;
    void *proc;
} displayControl_funcs_by_name[] = {
    {"FBPost", (void*)FBPost},
    {"postLayer", (void*)postLayer},
    {"postAllLayersDone", (void*)postAllLayersDone},
    {"getDisplayWidth", (void*)getDisplayWidth},
    {"getDisplayHeight", (void*)getDisplayHeight},
    {"getDisplayFPS", (void*)getDisplayFPS},
    {"getDisplayXDpi", (void*)getDisplayXDpi},
    {"getDisplayYDpi", (void*)getDisplayYDpi},
    {"postVirtualDisplay", (void*)postVirtualDisplay},
    {"postAllVirtualDisplaysDone", (void*)postAllVirtualDisplaysDone},
    {"postBoForScreenRecord", (void*)postBoForScreenRecord},
    {"postCaptureScreenColorBuffer", (void*)postCaptureScreenColorBuffer},
    {"authenticateMagic", (void*)authenticateMagic},
};
static const int displayControl_num_funcs = sizeof(displayControl_funcs_by_name) / sizeof(struct _displayControl_funcs_by_name);


#endif
