// Generated Code - DO NOT EDIT !!
// generated by 'emugen'

#ifndef GUARD_displayControl_encoder_context_t
#define GUARD_displayControl_encoder_context_t

#include "IOStream.h"
#include "displayControl_client_context.h"


#include <stdint.h>

struct displayControl_encoder_context_t : public displayControl_client_context_t {

    kmre::DisplayControl::IOStream *m_stream;
    displayControl_encoder_context_t(kmre::DisplayControl::IOStream *stream);
};

#endif  // GUARD_displayControl_encoder_context_t
