// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __displayControl_client_proc_t_h
#define __displayControl_client_proc_t_h



#include "displayControl_types.h"
#ifndef displayControl_APIENTRY
#define displayControl_APIENTRY 
#endif
typedef int32_t (displayControl_APIENTRY *FBPost_client_proc_t) (void * ctx, uint32_t, int32_t, int32_t, int32_t, int32_t);
typedef void (displayControl_APIENTRY *postLayer_client_proc_t) (void * ctx, const char*, uint32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
typedef int32_t (displayControl_APIENTRY *postAllLayersDone_client_proc_t) (void * ctx);
typedef uint32_t (displayControl_APIENTRY *getDisplayWidth_client_proc_t) (void * ctx);
typedef uint32_t (displayControl_APIENTRY *getDisplayHeight_client_proc_t) (void * ctx);
typedef uint32_t (displayControl_APIENTRY *getDisplayFPS_client_proc_t) (void * ctx);
typedef uint32_t (displayControl_APIENTRY *getDisplayXDpi_client_proc_t) (void * ctx);
typedef uint32_t (displayControl_APIENTRY *getDisplayYDpi_client_proc_t) (void * ctx);
typedef void (displayControl_APIENTRY *postVirtualDisplay_client_proc_t) (void * ctx, const char*, uint32_t, uint32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
typedef int32_t (displayControl_APIENTRY *postAllVirtualDisplaysDone_client_proc_t) (void * ctx);
typedef int32_t (displayControl_APIENTRY *postBoForScreenRecord_client_proc_t) (void * ctx, uint32_t, uint32_t, int32_t, int32_t, int32_t, int32_t);
typedef void (displayControl_APIENTRY *postCaptureScreenColorBuffer_client_proc_t) (void * ctx, uint32_t);
typedef int32_t (displayControl_APIENTRY *authenticateMagic_client_proc_t) (void * ctx, uint32_t);


#endif
