// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __displayControl_server_context_t_h
#define __displayControl_server_context_t_h

#include "displayControl_server_proc.h"

#include "displayControl_types.h"


struct displayControl_server_context_t {

	FBPost_server_proc_t FBPost;
	postLayer_server_proc_t postLayer;
	postAllLayersDone_server_proc_t postAllLayersDone;
	getDisplayWidth_server_proc_t getDisplayWidth;
	getDisplayHeight_server_proc_t getDisplayHeight;
	getDisplayFPS_server_proc_t getDisplayFPS;
	getDisplayXDpi_server_proc_t getDisplayXDpi;
	getDisplayYDpi_server_proc_t getDisplayYDpi;
	postVirtualDisplay_server_proc_t postVirtualDisplay;
	postAllVirtualDisplaysDone_server_proc_t postAllVirtualDisplaysDone;
	postBoForScreenRecord_server_proc_t postBoForScreenRecord;
	postCaptureScreenColorBuffer_server_proc_t postCaptureScreenColorBuffer;
	authenticateMagic_server_proc_t authenticateMagic;
	updateSharingScreenDisplay_server_proc_t updateSharingScreenDisplay;
	 virtual ~displayControl_server_context_t() {}
	int initDispatchByName( void *(*getProc)(const char *name, void *userData), void *userData);
};

#endif
