// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __displayControl_server_proc_t_h
#define __displayControl_server_proc_t_h



#include "displayControl_types.h"
#ifndef displayControl_APIENTRY
#define displayControl_APIENTRY 
#endif
typedef int32_t (displayControl_APIENTRY *FBPost_server_proc_t) (uint32_t, int32_t, int32_t, int32_t, int32_t);
typedef void (displayControl_APIENTRY *postLayer_server_proc_t) (const char*, uint32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
typedef int32_t (displayControl_APIENTRY *postAllLayersDone_server_proc_t) ();
typedef uint32_t (displayControl_APIENTRY *getDisplayWidth_server_proc_t) ();
typedef uint32_t (displayControl_APIENTRY *getDisplayHeight_server_proc_t) ();
typedef uint32_t (displayControl_APIENTRY *getDisplayFPS_server_proc_t) ();
typedef uint32_t (displayControl_APIENTRY *getDisplayXDpi_server_proc_t) ();
typedef uint32_t (displayControl_APIENTRY *getDisplayYDpi_server_proc_t) ();
typedef void (displayControl_APIENTRY *postVirtualDisplay_server_proc_t) (const char*, uint32_t, uint32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
typedef int32_t (displayControl_APIENTRY *postAllVirtualDisplaysDone_server_proc_t) ();
typedef int32_t (displayControl_APIENTRY *postBoForScreenRecord_server_proc_t) (uint32_t, uint32_t, int32_t, int32_t, int32_t, int32_t);
typedef void (displayControl_APIENTRY *postCaptureScreenColorBuffer_server_proc_t) (uint32_t);
typedef int32_t (displayControl_APIENTRY *authenticateMagic_server_proc_t) (uint32_t);
typedef int32_t (displayControl_APIENTRY *updateSharingScreenDisplay_server_proc_t) (uint32_t, int32_t, int32_t, int32_t, int32_t, int32_t);


#endif
