// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __GUARD_displayControl_opcodes_h_
#define __GUARD_displayControl_opcodes_h_

#define OP_FBPost                           10000
#define OP_postLayer                        10001
#define OP_postAllLayersDone                10002
#define OP_getDisplayWidth                  10003
#define OP_getDisplayHeight                 10004
#define OP_getDisplayFPS                    10005
#define OP_getDisplayXDpi                   10006
#define OP_getDisplayYDpi                   10007
#define OP_postVirtualDisplay               10008
#define OP_postAllVirtualDisplaysDone       10009
#define OP_postBoForScreenRecord            10010
#define OP_postCaptureScreenColorBuffer     10011
#define OP_authenticateMagic                10012
#define OP_updateSharingScreenDisplay       10013
#define OP_last                             10014


#endif
