// Generated Code - DO NOT EDIT !!
// generated by 'emugen'

#ifndef GUARD_displayControl_decoder_context_t
#define GUARD_displayControl_decoder_context_t

#include "IOStream.h" 
#include "displayControl_server_context.h"



struct displayControl_decoder_context_t : public displayControl_server_context_t {

	size_t decode(void *buf, size_t bufsize, kmre::DisplayControl::IOStream *stream);

};

#endif  // GUARD_displayControl_decoder_context_t
