// Auto-generated with: android/scripts/gen-entries.py --mode=funcargs host/libs/libDisplayControl/display_control_api.entries --output=/home/gfdgd_xi/Desktop/dde15/kylin-kmre-display-control/host/include/DisplayControl/display_control_api_functions.h
// DO NOT EDIT THIS FILE

#ifndef DISPLAY_CONTROL_API_FUNCTIONS_H
#define DISPLAY_CONTROL_API_FUNCTIONS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define LIST_DISPLAY_CONTROL_API_FUNCTIONS(X) \
  X(int, initDisplayControl, (const char* addr), (addr)) \
  X(int, stopDisplayControl, (), ()) \


#endif  // DISPLAY_CONTROL_API_FUNCTIONS_H
